[package]
name = "jsonptr"
version = "0.1.5"
edition = "2021"
description = "Data structures and logic for resolving, assigning, and deleting by JSON Pointers (RFC 6901)"
documentation = "https://docs.rs/jsonptr"
keywords = ["json-pointer", "rfc-6901", "6901"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/chanced/jsonptr"
homepage = "https://github.com/chanced/jsonptr"
authors = ["chance dinkins"]


[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
url = { version = "2", optional = true }
uniresid = { version = "0.1.4", optional = true }


[features]
default = []
std = ["serde/std", "serde_json/std"]
